using Algorithm;
// See https://aka.ms/new-console-template for more information
//Console.WriteLine("Hello, Alg!");

//BinSearch.run();
//RemoveElementsFromArray.Run();
//SquareOfSortedArray.Run();
//MinChildArray.Run();
//SumOfArraySection.Run();
//SeparateWeightedElement.Run();
//SpiralMatrix.Run();
//RemoveFromLinkedList.Run();
//InverseLinkedList.Run();
//ExchangeNode2By2.Run();
//RmoveFromReverse.Run();
//FindIntersection.Run();
//DetectLinkCycle.Run();
//ArePossitionDiffWords.Run();
//FindCommonLetters.Run();
//FindIntersectionOfArray.Run();
//HappyNumber.Run();
//FindNumbersForSum.Run();
//SumOf4ElemsFrom4Array.Run();
//RansomAndMagzine.Run();
//SumOfThreeElements.Run();
//SumOfFourNumberToSpecifiedValue.Run();
//ReverseString.Run();
//ReverseString2.Run();
//ReplaceNumberWithNumber.Run();
//RemoveExtraSpaces.Run();
//ReverseWordsOrderInAString.Run();
//RightRotateString.Run();
//FindStrInStr_kmp.Run();
IsStringComposedOfDuplecateStr.Run();